// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adxeyrhfjbfslwjfbasd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkeGV5cmhmamJmc2x3amZiYXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0NDE0NTgsImV4cCI6MjA3NTAxNzQ1OH0.66cC7cbi_GmYxWdN3ilJsSCLt2LJ3fMtCc36qJxcno4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});